version: '3.8'

services:
    app:
        build: .
        container_name: sequra-laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: sequra-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./public:/var/www/public
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: postgres:13
        container_name: sequra-postgres_db
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=sequra_user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=sequra_db
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network
    db-test:
        image: postgres:13
        container_name: sequra-postgres_db_test
        restart: unless-stopped
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=sequra_user_test
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=sequra_db_test
        volumes:
            - pgdata:/var/lib/postgresql/data_test
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge
